// Missão Prática - Nivel 3/livros-react/src/LivroLista.js
import React, { useState, useEffect, useMemo } from 'react';
import ControleLivro from './controle/ControleLivros'


function LinhaLivro(props) {
  const { livro, excluir } = props;

  return (
    <tr>
      <td>{livro.titulo} 
        <div className='.bg-danger'>
          <button type="button" class="btn btn-danger" onClick={() => excluir(livro.codigo)}>Excluir</button>
        </div>
      </td>
      <td>{livro.resumo}</td>
      <td>{livro.autor}</td>
      <td>{livro.editora}</td>
    </tr>
  );
}
export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  const controleLivro = useMemo(() => new ControleLivro(), []);

  useEffect(() => {
    if (!carregado) {
      setLivros(controleLivro.obterLivros());
      setCarregado(true);
    }
  }, [carregado, controleLivro]);

  const excluir = (codigoLivro) => {
    controleLivro.excluir(codigoLivro);
    setCarregado(false);
  };

  return (
    <main>
      <h1>Catálogo de Livros</h1>
      <table class="table table-striped ">
        <thead class="thead-dark">
          <tr>
            <th >Título</th>
            <th class="w-50 p-2">Resumo</th>
            <th>Autor</th>
            <th>Editora</th>
            
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
          ))}
        </tbody>
      </table>
    </main>
  );
}

// Missão Prática - Nível 4/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir(codigoLivro: number): void {
    this.servLivros.excluir(codigoLivro);
    this.livros = this.servLivros.obterLivros();
  }

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora);
  }
}
<main>
  <h2>Catálogo de Livros</h2>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Resumo</th>
        <th scope="col">Editora</th>
        <th scope="col">Autores</th>  
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }} <div><br></div>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">
          Excluir
          </button></td>
        
        <td class="w-50 p-2">{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>
<style>
  main{
    margin: auto;
    width: 70%;
  }
  h2{
    font-size: 70px;
  }
</style>
